/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

// Register definitions for STM32F767
#define RCC_BASE        0x40023800
#define GPIOB_BASE      0x40020400

#define RCC_AHB1ENR     (*(volatile uint32_t*)(RCC_BASE + 0x30))
#define GPIOB_MODER     (*(volatile uint32_t*)(GPIOB_BASE + 0x00))
#define GPIOB_ODR       (*(volatile uint32_t*)(GPIOB_BASE + 0x14))

#define GPIOB_EN        (1 << 1)  // Bit 1 for GPIOB
#define PB7_MODER       (1 << 14) // Pin 7, output mode

void delay(uint32_t count) {
    while (count--) {
        __asm("nop");
    }
}

int main(void)
{
    // Enable clock for GPIOB
    RCC_AHB1ENR |= GPIOB_EN;

    // Set PB7 as output
    GPIOB_MODER |= PB7_MODER;

    /* Infinite loop */
    while (1) {
        // Toggle PB7
        GPIOB_ODR ^= (1 << 7);
        // Delay
        delay(1000000);
    }
}
